addons:
  apt:
    packages:
    - swig

language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
#  - "pypy"
# command to install dependencies
before_install:
  - ./setup_sources.sh
  - ./setup_package.sh
install:
  - cd xraylib
  - python setup.py sdist
  - cd ..
#  - find . -name "*.tar*"
  - pip install ./xraylib/dist/xraylib-3.1.tar.gz
script:
  - python -c "import xraylib"
